--- 
- name: Creates ec2 instances 
  hosts: localhost
  tasks:
    - name: Create instances 
      ec2:
        key_name: "{{pairing_key}}"
        instance_type: "{{instance_type}}"
        image: "{{image_of_instance}}"
        count: 3
        vpc_subnet_id: "{{subnet}}"
        region: "{{region}}"