---
- name: creates ec2 instances
  hosts: localhost
  tasks: 
  vars_prompt:
    - name: ec2_var
      ec2:
        key_name: "{{key_name}}"
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        count: "{{count}}"
        vpc_subnet_id: "{{vpc_subnet_id}}"
        region: "{{region}}"
        #user_data: "{{ lookup('file', 'user_date.sh') }}"