---
- name: install wordpress
  become: yes
  become_method: sudo
  gather_facts: no
  ignore_errors: true
  hosts: web
  connection: ssh
  tasks:
    - name: Install neccessary packages
      package:
        name: "{{item}}"
        state: latest
      with_items:
        - php-gd
        - httpd
        - mysql
        - mariadb-server
        - php
        - php-mysql
        - php-fpm
        - wget
        - unzip
        - APACHERESTART7
      ignore_errors: true
    - name: download 1 package
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: /tmp/
    -name: unzip wordpress file
     unarchive:
       src: "/tmp/wordpress-5.2.1.tar.gz"
       dest: /var/www/html/
       remote_src: yes
     become: yes
     become_method: sudo

    -name: Move files to html folder
     shell: mv /var/www/html/wordpress/* /var/www/html
     become: yes
     become_method: sudo
     ignore_errors: yes

    -name: restart httpd
     systemd:
       name: httpd
       state: started
       enabled: true
     become: yes
     become_method: sudo
    - name: APACHERESTART7
      when: ( ansible_disribution == "CentOS" ansible_distribution_major_version == "7" )
      systemd:
        name : httpd
        state: restarted
      ignore_errors: true
