- block:  
  - name: create r1soft
    copy: 
      src: r1soft.repo
      dest: /etc/yum.repos.d/r1soft.repo

  - name: Install r1soft agent
    package: 
      name: serverbackup-enterprise-agent
      state: present
    
          
  - name: start agent
    service: 
      name: sbm-agent
      state: restarted

  - name: get key
    shell: "r1soft-setup --get-key http://r1soft.acirrustech.com"
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"