---
- name: create instance , create image, copy image, launch machine on image
  hosts: localhost
  gather_facts: true
  vars_files: task1_vars
  tasks:
    - name: Create intance for You
      ec2:
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        count: "{{count}}"
        vpc_subnet_id: "{{vpc_subnet_id}}"
        region: "{{region}}"
        wait: yes
      register: ec2
    - debug: 
        msg: ec2
    
    - name: create authorized_key file
      file:
        path: "/home/centos/.ssh/authorized_keys"
        mode: 0600
        state: touch
        owner: "centos"

    - name: add public key
      lineinfile:
        path: "/home/centos/.ssh/authorized_keys"
        line: "{{line}}"     
  
  
    - name: copy instance id to another variable
      debug: var={{ item.id }}
      with_items:
       - "{{ ec2.instances }}"
      register: instanceid


    
    
    
    - name: create image of instance
      ec2_ami:
        instance_id: "{{ instanceid.instances }}"
        wait: no
        name: image