---
- name: create instance , create image, copy image, launch machine on image
  hosts: localhost
  gather_facts: true
  vars_files: task1/task1_vars
  tasks:
    - name: Create intance for You
      ec2:
        name: "{{name}}"
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        count: "{{count}}"
        vpc_subnet_id: "{{vpc_subnet_id}}"
        region: "{{region}}"
        key_material: "{{key_material}}"      

    - name: Create image for you
      ec2_instance_facts:
        filters:
          tag: "{{name}}"
          instance_ids:
