---
- name: create instance , create image, copy image, launch machine on image
  hosts: localhost
  gather_facts: true
  vars_files: task1_vars
  tasks:
    - name: Create intance for You
      ec2:
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        count: "{{count}}"
        vpc_subnet_id: "{{vpc_subnet_id}}"
        region: "{{region}}"
        key_material: "{{key_material}}"      