---
- name: create instance , create image, copy image, launch machine on image
  hosts: localhost
  gather_facts: true
  vars_files: task1_vars
  tasks:
    - name: Create intance for You
      ec2:
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        count: "{{count}}"
        vpc_subnet_id: "{{vpc_subnet_id}}"
        region: "{{region}}"
        instance_tags:
          Name: L0L
        wait: yes
  #    register: ec2
  #  - debug: 
  #      msg: "{{ec2}}"
    
    - name: create authorized_key file
      file:
        path: "/home/centos/.ssh/authorized_keys"
        mode: 0600
        state: touch
        owner: "centos"

    - name: add public key
      lineinfile:
        path: "/home/centos/.ssh/authorized_keys"
        line: "{{line}}"

    - name: Gather facts
      ec2_instance_facts:
       region: "{{region}}"
       filters:
         "tag:Name": L0L
      register: my_instance

    - name: Display Instance Facts
      debug:
        msg: "{{ item }}"
      with_items:
       - "{{my_instance.instances[0].instance_id}}"
      
    
 
    - name: create image of instance
      ec2_ami:
        region: us-west-2
        state: present
        instance_id: "{{ my_instance.instances[0].instance_id  }}"
        wait: yes
        name: Cool
  




    - name: copy image to another region
      ec2_ami_copy:
        source_region: "{{region}}"
        region: "{{copy_ami_region}}"
        source_image_id: "{{my_awesome_ami[0].image_id}}"
        name: copy_ami
        description: latest_copied_ami
        encrypted: yes

    - name: Launch pre-configured instance in another region
      ec2:
        image: "{{my_awesome_ami[0].image_id}}"
        count: "{{new_count}}"
        vpc_subnet_id: "{{new_vpc_subnet_id}}"
        region: "{{copy_ami_region}}"
        instance_tags:
          Name: "{{name}}"
        wait: yes


