---
- name: Provision ec2 instances
  hosts: all
  become: yes
  become_user: root
  tasks: 
    - name: Ping the server
      ping:

- name: Install r1soft agent
  import_playbook: r1soft_agent.yaml
- name: nagiosxi agent
  import_playbook: nagiosxi_agent.yaml
- name: filebeat
  import_playbook: filebeat.yaml