---
- name: this will build whole infrastructure for you
  hosts: localhost
  gather_facts: yes
  vars_files: IAAS_vars
  tasks:
    
    - name: create ssh key in different regions
      ec2_key:
        name: key
        key_material: "{{key_material}}"
        region: "{{ item }}"
      loop:
        - "{{key_region_1}}"
        - "{{key_region_2}}"
        - "{{key_region_3}}"
        
    - name: create vpc in region

      ec2_vpc_net:
        name: "vpc_name"
        cidr_block: "{{vpc_cidr_block}}"
        region: "{{vpc_region}}"
        tags: 
          module: "{{environment_name}}"
      register: vpc
      
    - name: display vpc facts
      debug:
        msg: "{{item}}"
      with_items:
      - "{{vpc}}"
        



      # ec2_vpc_subnet:
      #   state: present
      #   vpc_id: 
        
      


    
    # - name: create security group
    #   ec2_group:
    #     name: "{{security_group_name}}"
    #     description: "{{description}}"
    #     vpc_id: 
    #     region: "{{vpc_region}}"
    #     rules:
    #       - proto: tcp
    #         from_port: 80
    #         to_port: 80
    #         cidr_ip: 0.0.0.0/0
    #       - proto: tcp
    #         from_port: 22
    #         to_port: 22
    #         cidr_ip: 0.0.0.0/0