---
- name: this will build whole infrastructure for you
  hosts: localhost
  gather_facts: yes
  vars_files: IAAS_vars
  tasks:
    
    - name: create ssh key in different regions
      ec2_key:
        name: key
        key_material: "{{key_material}}"
        region: "{{ item }}"
      loop:
        - "{{key_region_1}}"
        - "{{key_region_2}}"
        - "{{key_region_3}}"
        
    - name: create vpc in region
      ec2_vpc:
        state: present
        cidr_block: "{{vpc_cidr_block}}"
        resource_tags: "{{environment_name}}"
        subnets:
          - cidr: "{{subnet_cidr_a}}"
            az: "{{az_a}}"
          - cidr: "{{subnet_cidr_b}}"
            az: "{{az_b}}"
          - cidr: "{{subnet_cidr_c}}"  
            az: "{{az_c}}"
        internet_gateway: True
        route_tables:
          - subnets:
              - "{{subnet_cidr_a}}"
              - "{{subnet_cidr_b}}"
              - "{{subnet_cidr_c}}"  
            routes:
              - dest: 0.0.0.0/0
                gw: igw
        region: "{{vpc_region}}"
      register: vpc


    
    - name: create security group
      ec2_group:
        name: "{{security_group_name}}"
        description: "{{description}}"
        vpc_id: 
        region: "{{vpc_region}}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0